server.port=9876
server.servlet.context-path=/soa/api/v1

spring.application.name=soa-lab

spring.datasource.url=jdbc:postgresql://localhost:5432/soa
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

#logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG